env:
  es2017: true
  browser: true
  commonjs: true

extends: ['htmlacademy/es6', 'plugin:react/recommended', 'plugin:@typescript-eslint/recommended']

parserOptions:
  ecmaFeatures:
    tsx: true
  ecmaVersion: 2018
  sourceType: module

plugins: ['react']

settings:
  react:
    version: '16'

rules: {"no-console": "off"}
